In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Standard Scaler in Scikit-Learn

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)


StandardScaler()

In [7]:
standardScaler.mean_

array([5.92416667, 3.03583333, 3.9125    , 1.25      ])

In [11]:
standardScaler.scale_

array([0.81034929, 0.43297341, 1.69845825, 0.7285831 ])

In [13]:
X_train = standardScaler.transform(X_train)

In [14]:
X_test_standard = standardScaler.transform(X_test)

In [15]:
 from sklearn.neighbors import KNeighborsClassifier

In [16]:
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)
clf.score(X_test_standard, y_test)

0.9666666666666667

In [17]:
clf.score(X_test,y_test)

0.26666666666666666

In [18]:
X.shape[0]

150

In [19]:
X.shape[1]

4

# You can also ues MinMaxScaler