In [4]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from math import sqrt
from collections import Counter
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)
x = np.array([8.093607318, 3.365731514])
x = x.reshape(1,-1)
x

array([[8.09360732, 3.36573151]])

In [13]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [14]:
kNN_classifier.predict(x)

array([1])

In [3]:
class kNNClass:
    def __init__(self,k):
        self.k = k
        self._X_train = None
        self._y_train = None
    def fit(self, X_train, y_train):
        self._X_train = X_train
        self._y_train = y_train
    def predict(self, X_predict):
        y_predict = [self._predict(x) for x in X_predict]
        return np.array(y_predict)
    def _predict(self, x):
        distances = [sqrt(np.sum((x_train - x)**2)) for x_train in self._X_train]
        nearest = np.argsort(distances)
        topK_y = [self._y_train[i] for i in nearest[:self.k]]
        votes = Counter(topK_y)
        return votes.most_common(1)[0][0]

In [5]:
knnclassifier = kNNClass(6)
knnclassifier.fit(X_train, y_train)
knnclassifier.predict(x)

array([1])